### ISSUE TITLE
Reason: image not found

### ISSUE THREAD

**Issue by walter211** [fairingrey/actix-realworld-example-app#10]
diesel database setup

**Comment by fairingrey** [comment]
I'm sorry, do you have trouble with something? Not sure what this issue is for.

**Comment by walter211** [comment]
when I follow readme to launch this proj, after run `diesel database setup`, It gives error "Reason: image not found"

**Comment by walter211** [comment]
I wonder to know if I lost any step for installing all dependencies

**Comment by fairingrey** [comment]
I'm not sure what to tell you -- I don't think that kind of error message exists anywhere in the Diesel CLI.

You're going to have to be more clear. You have the correct diesel CLI installed, right? Type in `which diesel` and `diesel --version` and make sure it says something like:

```
 allen@harumi  ~/Projects   master ●  which diesel
/home/allen/.cargo/bin/diesel
 allen@harumi  ~/Projects   master ●  diesel --version
diesel 1.4.0
```

On Windows, you may see it as something like `%USERPROFILE%/.cargo/bin/diesel`.

If not, you'll have to figure out how to install the diesel CLI properly. Make sure you are running this command in the root of this project (where the "migrations" folder is).

**Comment by walter211** [comment]
That's it. 
`
#which diesel
/Users/xxx/.cargo/bin/diesel
`
`
#diesel version
dyld: Library not loaded: @rpath/libmysqlclient.21.dylib
  Referenced from: /Users/xxx/.cargo/bin/diesel
  Reason: image not found
Abort trap: 6
`
thx, seems that I need make a deeper searching for diesel installation.

**Comment by fairingrey** [comment]
I don't cover how to install the diesel CLI in my guide, since the link to their page should describe it all. But if you are only using postgres and your postgres paths are properly linked in your environment, it should work. Since it looks like you've figured it out, I'll be closing this issue.
