### ISSUE TITLE
migrate to actix-web 1.0

### ISSUE THREAD

**Issue by fairingrey** [fairingrey/actix-realworld-example-app#13]
With the release of actix-web 1.0 (a major point release!), this repo should be migrated to use the updated dependency.

**Comment by geropl** [comment]
Hi @fairingrey , I'd like to give it a stab.

**Comment by fairingrey** [comment]
@geropl Go for it! I've been busy with other things (mostly work, and probably focusing on Rust async projects otherwise), so any help would be much appreciated. Feel free to ask for help, although I might not be able to offer much
